const navy = '#0F3659';
export const style = {
  singleDataWrapper: {
    height: 'fit-content',
    marginTop: '10px',
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
  },
  editBtnWrapper: {
    padding: '0px',
    margin: '0px',
    paddingRight: '10px',
    width: '100%',
    display: 'flex',
    justifyContent: 'end',
    borderBottomLeftRadius: '10px',
    borderBottomRightRadius: '10px',
    minWidth: '1140px',
  },
  dataFieldColumn: {
    backgroundColor: '#9e9e9e',
    height: '33px',
    borderRight: '1px solid rgb(174, 168, 168)',
    borderBottom: '1px solid #fafafa',
    padding: '4px 5px',
  },
  dataExpColumn: {
    backgroundColor: '#757575',
    height: '33px',
    borderRight: '1px solid rgb(174, 168, 168)',
    borderBottom: '1px solid #fafafa',
    padding: '4px 5px',
    color: 'white',
  },
  dataFieldContainer: {
    backgroundColor: '#eeeeee',
    height: '100%',
    borderRight: '1px solid rgb(174, 168, 168)',
    borderBottom: '1px solid #fafafa',
    padding: '4px 5px',
  },
  dataContainer: {
    height: '33px',
    borderBottom: '0.8px solid #e0e0e0',
    width: '',
    borderRight: '0.8px solid #e0e0e0',
    padding: '4px 5px',
    display: 'flex',
  },
  completeBtn: {
    border: `1px solid ${navy}`,
    color: `${navy}`,
    borderRadius: '5px',
    width: '60px',
    height: '35px',
  },
  editBtn: {
    backgroundColor: `${navy}`,
    border: 'none',
    color: 'white',
    borderRadius: '5px',
    width: '60px',
    height: '35px',
  },
  acceptBtn: {
    backgroundColor: '#00e676',
    color: 'white',
    fontSize: '15px',
    borderRadius: '5px',
    width: '80px',
    height: '35px',
  },
  rejectBtn: {
    backgroundColor: '#e53935',
    color: 'white',
    fontSize: '15px',
    borderRadius: '5px',
    width: '80px',
    height: '35px',
    marginLeft: '10px',
    marginRight: '10px',
  },
  addButton: {
    backgroundColor: '#32CD32',
    color: 'white',
    fontSize: '15px',
    borderRadius: '5px',
    width: '100px',
    height: '35px',
    marginRight: '10px',
    border: 'none',
  },
  deleteButton: {
    backgroundColor: '#e53935',
    color: 'white',
    fontSize: '15px',
    borderRadius: '5px',
    width: '100px',
    height: '35px',
    marginRight: '10px',
    border: 'none',
  },
};
export const divStyle = {
  loadingBackground: {
    position: 'absolute',
    width: '100vw',
    height: '100vh',
    top: 0,
    left: 0,
    backgroundColor: '#ffffffb7',
    zIndex: 999,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: '25px',
    textAlign: 'center',
  },
  errorContainer: {
    height: '65vh',
    minHeight: '500px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  errorText: {
    fontSize: '16px',
    textAlign: 'center',
  },
};
export default style;
